README.md
context.go
poteto.go

https://github.com/poteto0/poteto/issues/58

CHANGE: using cache of context

---

CHANGELOG.md
README.md
error_handler.go
middleware/cors_test.go
middleware/timeout.go
middleware/timeout_test.go
response.go
response_test.go

it will require `>=0.17.0`
https://github.com/poteto0/poteto/issues/39

Timeout middleware

---

CHANGELOG.md
README.md
route.go
route_test.go

If collision occurr -> poteto warn that.
And initialize with before function

FUNC: warn collision Detection

---

CHANGELOG.md
README.md
app_test.go
handler_func.go
leaf.go
leaf_test.go
middleware/README.md
poteto.go

- FEATURE: `Poteto.Leaf(path, handler)` make router great
- DOCUMENT: Update some document
```go
func main() {
p := poteto.New()
p.Leaf("/users", func(userApi poteto.Leaf) {
userApi.Register(sampleMiddleware)
userApi.GET("/", getAllUserForTest)
userApi.POST("/create", getAllUserForTest)
userApi.PUT("/change", getAllUserForTest)
userApi.DELETE("/delete", getAllUserForTest)
})
p.Run(":8080")
}
```
It will be included `>=0.21.0`
#66

`Poteto.Leaf(path, handler)` Make Router Great

---

CHANGELOG.md
README.md
leaf.go
leaf_test.go
poteto.go
poteto_test.go
router.go
router_test.go

- OPTIMIZE: optimize router's structure & faster
- FEATURE: Now, poteto follows patch, head, options, trace, and connect
- DOCUMENT: update some document
- Nothing to do
- Now supports as bellow
```go
p.PATCH("/path", handler)
p.HEAD("/path", handler)
p.OPTIONS("/path", handler)
p.TRACE("/path", handler)
p.CONNECT("/path", handler)
```
It will be included `>=0.23.2`
- https://github.com/poteto0/poteto/issues/89
- https://github.com/poteto0/poteto/issues/107

Router's internal structure is optimized & support all faster

---

CHANGELOG.md
README.md
route.go

- OPTIMIZE: performance tuning by @poteto0
#113

Searchのパフォーマンスチューニング

---

context.go
ip_handler.go
middleware/jws.go
router.go
utils/cushion.go

- appropriate error messages
It will be included `>=0.25.1`
https://github.com/poteto0/poteto/issues/138

appropriate error messages ( エラーの内容を具体化する

---

poteto_rpc.go
poteto_rpc_test.go
utils_for_test.go

- BUG: fix `PotetoJSONRPCAdapter` dosen't check class.
It will be included `v0.26.1`.
#157

`PotetoJSONRPCAdapter`がクラスをチェックしない問題の修正

---

cmd/engine/new.go
cmd/engine/new_test.go
cmd/template/jsonrpc.go
cmd/template/jsonrpc_fast.go

- FEAT: `poteto-cli new -j | --jsonrpc` gen jsonrpc template
It will be included `0.26.3`
#159

FEAT: -j | --jsonrpc gen jsonrpc template

---

cmd/engine/new.go
cmd/engine/new_test.go
cmd/template/docker.go
cmd/template/docker_compose.go

- FEAT: -d | --docker gen with Dockerfile & docker-compose.yaml
It will be included `0.26.3`
#167

FEAT: -d | --docker gen with Dockerfile & docker-compose.yaml

---

.devcontainer/devcontainer.json
.devcontainer/scripts/postCreateCommand.sh

- CHANGE: devcontainer.json to show git branch
#190

CHANGE: devcontainer.json

---

.devcontainer/Dockerfile
.github/workflows/test-1_21.yaml
.github/workflows/test-1_22.yaml
.github/workflows/test-1_23.yaml
go.mod

https://github.com/poteto-go/poteto/issues/205

Poteto's go version update

---

binder.go
error_handler.go
http_param.go
poteto.go
poteto_rpc.go
rules/.golangci.yaml
utils/cushion.go

- https://github.com/poteto-go/poteto/issues/248

リンターに基づいたリファクタリング

---

http_param.go

Memory optimization of httpParams
httpParams was using large memory during initialization.
- https://github.com/poteto-go/poteto/issues/241

httpParamsのメモリ最適化

---

app_test.go
leaf_test.go
poteto.go
poteto_test.go
utils_for_test.go

- FEAT: Middleware chain -> `p.Chain(middlewares)(handler)`
```go
func main() {
p := poteto.New()
p.GET(
"/users",
p.Chain(
middleware1,
middleware2,
)(handler)
)
}
```
- https://github.com/poteto-go/poteto/issues/254

`p.Chain(middlewares)(handler)` make your handler great

---

poteto.go
poteto_test.go

- FEAT: check handler is defined `p.Check(method, path) bool`
```go
func main() {
p := poteto.New()
p.GET("/users", handler)
ok := p.Check(http.MethodGet, "/users") // -> return true
ng := p.Check(http.MethodPost, "/users") // -> return false
}
```
- #253

FEAT: check handler is defined `p.Check(method, path) bool`

---

.github/pull_request_template.md
CHANGELOG.md
constant/constants.go
constant/old_constants.go

rel: prepare -> 1.7.0

---

CHANGELOG.md
constant/constants.go
constant/old_constants.go

prepare -> 1.8.0

---

README.md

doc: update about readme

---

CHANGELOG.md
SECURITY.md
constant/constants.go
constant/old_constants.go

rel: prepare -> 1.9.0

---

oidc/verify.go
oidc/verify_test.go

patch: if not cached

---

context_test.go
http_param.go

- change: http params to be public for ut

change: http params to be public for ut

---

CHANGELOG.md
constant/constants.go
constant/old_constants.go

rel: prepare -> v1.10.2

---

CHANGELOG.md
SECURITY.md
constant/constants.go
constant/old_constants.go

rel: prepare -> 1.11.0

---

context.go
context_benchmark_test.go
context_test.go
http_param.go
http_param_test.go
poteto.go
response.go
utils/math.go
utils/math_test.go

- pef: memory allocate optimized
- https://github.com/poteto-go/poteto/issues/316

pef: memory allocate optimized
